### ISSUE TITLE
Failed config

### ISSUE THREAD

**Issue by behnam85** [mampfes/esphome_obis_d0#1]
hello,

when i  use multiple UART buses esphome fail config.

Failed config

sml: None
  
  Too many candidates found for 'uart_id' type 'uart::UARTComponent' Some are 'my_uart', 'my_uart1'.
  []

#################################################
esphome:
  name: sml-32

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

web_server:
  port: 80
  local: true

api:
  

ota:
  password: "86ad66ea5b9b72bccf57812ec0157368"

wifi:
  ssid: Mi wifi1
  password: behnam123
  
  ap: {}  

captive_portal:
    
external_components:
  - source:
      type: local
      path: components
    components: [ obis_d0 ]
    
uart:
  - id: my_uart
    rx_pin: GPIO16
    tx_pin: GPIO17
    baud_rate: 300
    data_bits: 7
    parity: EVEN
    stop_bits: 1
  - id: my_uart1
    rx_pin: GPIO19
    tx_pin: GPIO18
    baud_rate: 300
    data_bits: 7
    parity: EVEN
    stop_bits: 1
  

  

  
obis_d0:
  - id: my_sm
    uart_id: my_uart
  - id: my_sm1
    uart_id: my_uart1
  

sensor:
  - platform: obis_d0
    name: "Positive active energy (A+) total"
    obis_d0_id: my_sm
    obis_code: "\x021.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    state_class: total_increasing
    device_class: energy
    value_regex: "\\d{6}\\.\\d{2}\\*kWh"
    
  - platform: obis_d0
    name: "active energy (A+) in tariff T1"
    obis_d0_id: my_sm
    obis_code: "1.8.1"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    state_class: total_increasing
    device_class: energy
    value_regex: "\\d{6}\\.\\d{2}\\*kWh"  
    
  - platform: obis_d0
    name: "active energy (A+) in tariff T2"
    obis_d0_id: my_sm
    obis_code: "1.8.2"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    state_class: total_increasing
    device_class: energy
    value_regex: "\\d{6}\\.\\d{2}\\*kWh"  
    
  - platform: obis_d0
    name: "active energy (A+) in tariff T3"
    obis_d0_id: my_sm
    obis_code: "1.8.3"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    state_class: total_increasing
    device_class: energy
    value_regex: "\\d{6}\\.\\d{2}\\*kWh"
    
    
  - platform: obis_d0
    name: "active energy (A+) in tariff T4"
    obis_d0_id: my_sm
    obis_code: "1.8.4"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    state_class: total_increasing
    device_class: energy
    value_regex: "\\d{6}\\.\\d{2}\\*kWh"  
    
    
    
  - platform: obis_d0
    name: "reactive energy (Q+) total"
    obis_d0_id: my_sm
    obis_code: "3.8.0"
    unit_of_measurement: kvarh
    accuracy_decimals: 4
    state_class: total_increasing
    device_class: energy
    value_regex: "\\d{6}\\.\\d{2}\\*kvarh"  
    
  - platform: obis_d0
    name: "reactive energy (Q+) in tariff T1"
    obis_d0_id: my_sm
    obis_code: "3.8.1"
    unit_of_measurement: kvarh
    accuracy_decimals: 4
    state_class: total_increasing
    device_class: energy
    value_regex: "\\d{6}\\.\\d{2}\\*kvarh"
    
    
  - platform: obis_d0
    name: "reactive energy (Q+) in tariff T2"
    obis_d0_id: my_sm
    obis_code: "3.8.2"
    unit_of_measurement: kvarh
    accuracy_decimals: 4
    state_class: total_increasing
    device_class: energy
    value_regex: "\\d{6}\\.\\d{2}\\*kvarh"  
    
  - platform: obis_d0
    name: "reactive energy (Q+) in tariff T3"
    obis_d0_id: my_sm
    obis_code: "3.8.3"
    unit_of_measurement: kvarh
    accuracy_decimals: 4
    state_class: total_increasing
    device_class: energy
    value_regex: "\\d{6}\\.\\d{2}\\*kvarh"  
    
    
  - platform: obis_d0
    name: "reactive energy (Q+) in tariff T4"
    obis_d0_id: my_sm
    obis_code: "3.8.4"
    unit_of_measurement: kvarh
    accuracy_decimals: 4
    state_class: total_increasing
    device_class: energy
    value_regex: "\\d{6}\\.\\d{2}\\*kvarh"  
      
  - platform: obis_d0
    name: "active maximum demand (A+) total"
    obis_d0_id: my_sm
    obis_code: "1.6.0"
    unit_of_measurement: kW
    accuracy_decimals: 4
    state_class: total_increasing
    device_class: energy
    value_regex: "\\d{3}\\.\\d{3}\\*kW"  
    
    
  - platform: obis_d0
    name: "reactive maximum demand (Q+) total"
    obis_d0_id: my_sm
    obis_code: "3.6.0"
    unit_of_measurement: kvar
    accuracy_decimals: 4
    state_class: total_increasing
    device_class: energy
    value_regex: "\\d{3}\\.\\d{3}\\*kvar"    
    
  - platform: uptime
    name: Uptime
    id: uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str(); 
    
    
    
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s  
    

text_sensor:
  - platform: obis_d0
    name: "Device Identification"
    obis_d0_id: my_sm
    obis_code: "C.1.0"
    
    value_regex: "\\w{16}"
    
  - platform: template
    name: Uptime
    id: uptime_human
    icon: mdi:clock-start  
    
  
  - platform: version
    name: "Version"  
    
  ##############################
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    bssid:
      name: Connected BSSID
    mac_address:
      name: Mac Wifi Address
    scan_results:
      name: Latest Scan Results
    
    
    
    
    

binary_sensor:
  - platform: status
    name: "obis reader status"   
    
##################################

  - platform: gpio
    pin: GPIO34
    name: "Cover alarm"
    device_class: window
    
    
    

switch:
  - platform: restart
    name: "obis reader Restart"    
    
    
output:
  - platform: gpio
    pin: 5
    id: output1

button:
  - platform: output
    name: "Get data "
    output: output1
    duration: 500ms 
    on_press:
      then:
      - uart.write:
         id: my_uart
         data: [0x2F, 0x3F, 0x21, 0x0D, 0x0A]  
      - delay: 1s
      - uart.write:
         id: my_uart
         data: [0x06, 0x30, 0x30, 0x30, 0x8D, 0x0A]

**Comment by mampfes** [comment]
Please check if this fix works for you.

**Comment by behnam85** [comment]
Hello . There is no error in compilation.
thanks for solving this problem.
