### ISSUE TITLE
Connection two Sensors to one ESP

### ISSUE THREAD

**Issue by mobilutz** [mampfes/esphome_obis_d0#14]
I am having an issue, with connecting two sensors to one ESP.

One of the sensors in using this esphome component, another one is using the esphome integrated SML component - https://esphome.io/components/sml.html

In the SML component, I can set a `server_id`. But this is not configurable here. 

Is there a way to add the `server_id` here as well?

Thanks
Lutz

PS: Writing in english, as this is my programming language 😉

**Comment by mampfes** [comment]
According to the documentation is SML a bus, so you can connect multiple energy meters to one bus. Then the optional `server_id` is needed to differentiate the meters.
Whereas D0 is a point-to-point connection, so there can be only one meter per UART. Therefore you don't need an extra `server_id`.
Does this makes sense to you?

**Comment by mampfes** [comment]
Any update?
