### ISSUE TITLE
Interval?

### ISSUE THREAD

**Issue by hvorragend** [mampfes/esphome_obis_d0#18]
Hi, 
to be honest: I didn't try your solution yet. 
I am currently using the Vzlogger2Mqtt-addon. 
For me it es quite important, that I can slower the pushed values to HA. My smart meter is sending in a 5-sec-interval. Too much data. And I don't' want to use HA filters to keep the database slim. 

Is it possible to just send smart meter events in a 60s interval to HA?

Thank you.

**Comment by mampfes** [comment]
This is not supported by the component itself, but should be feasible with the esphome sensor filters:
https://esphome.io/components/sensor/index.html#sensor-filters

**Comment by hvorragend** [comment]
Thank you.
