### ISSUE TITLE
Problems with more than 2 Smart Meters.

### ISSUE THREAD

**Issue by MaxderLange2008** [mampfes/esphome_obis_d0#20]
After I add the third Smart Meter to the Code the ESP32 won't come online anymore. It seems like its restarting several times. Every entry of the three works on their own and with another one in combination. My end goal are 5 Smart Meters on the ESP32.
Greetings, Max.

**Comment by mampfes** [comment]
Maybe the ESP32 runs out of memory. Did you already set the option `optimize_size` to `true`?
What you can also do is to reduce the number of sensors.

**Comment by MaxderLange2008** [comment]
I figured it out. It was because the ESP32 supports three hardware UART devices. One of them is used for the logger, and the other two were available. Unfortunately, there is no solution to this at the moment because software UART is not implemented for the ESP32. I disabled the logger, and the number of working Energy Meters went up to three. The remaining two are now being read out by another ESP32 that I already had.
Greetings, Max.
