### ISSUE TITLE
OBIS info: \0332r:S;.7.0*255 -> 0]-L(kR:3

### ISSUE THREAD

**Issue by jcollasius** [mampfes/esphome_obis_d0#4]
Worked flawless on my eBZ DD3] smartmeter for some hours.
Now I get this error(s) and no values at all.

[00:24:36][D][obis_d0:177]: OBIS value start missing
[00:24:36][D][obis_d0:165]: OBIS value end missing
[00:24:37][D][obis_d0:124]: invalid end or record
[00:24:37][D][obis_d0:124]: invalid end or record
[00:24:37][D][obis_d0:124]: invalid end or record
[00:24:37][D][obis_d0:185]: OBIS info: \0332r:S;.7.0*255 -> 0]-L(kR:3
[00:24:37][D][obis_d0:124]: invalid end or record

Powercyle didn't help. Tried my old vzlogger installation and vzlogger is working.
Any Ideas?

**Comment by jcollasius** [comment]
`external_components:
#  - source: github://mampfes/esphome_obis_d0
  - source:
      type: local
      path: my_components

uart:
  id: uart_gpio16
  rx_pin: GPIO16
  baud_rate: 9600
  data_bits: 7
  parity: EVEN
  stop_bits: 1

obis_d0:
  id: smartmeter
  uart_id: uart_gpio16

#text_sensor:
#  - platform: obis_d0
#    name: "Device Identification"
#    obis_d0_id: smartmeter
#    obis_code: "1-0:96.1.0*255"
#    entity_category: diagnostic
#    value_regex: "\\w{14}"

sensor:
#  - !include common/sensor/wifi.yaml
#  - !include common/sensor/uptime.yaml

  - platform: obis_d0
    name: "Smartmeter Provided Energy"
    obis_d0_id: smartmeter
    obis_code: "1-0:1.8.0*255"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    state_class: total_increasing
    device_class: energy
    value_regex: "\\d{6}\\.\\d{8}\\*kWh"

  - platform: obis_d0
    name: "Smartmeter Power"
    obis_d0_id: smartmeter
    obis_code: "1-0:16.7.0*255"
    unit_of_measurement: W
    accuracy_decimals: 2
    state_class: measurement
    device_class: energy
    value_regex: "\\d{6}\\.\\d{2}\\*W"

  - platform: obis_d0
    name: "Smartmeter Power L1"
    obis_d0_id: smartmeter
    obis_code: "1-0:36.7.0*255"
    unit_of_measurement: W
    accuracy_decimals: 2
    state_class: measurement
    device_class: energy
    value_regex: "\\d{6}\\.\\d{2}\\*W"

  - platform: obis_d0
    name: "Smartmeter Power L2"
    obis_d0_id: smartmeter
    obis_code: "1-0:56.7.0*255"
    unit_of_measurement: W
    accuracy_decimals: 2
    state_class: measurement
    device_class: energy
    value_regex: "\\d{6}\\.\\d{2}\\*W"
    
  - platform: obis_d0
    name: "Smartmeter Power L3"
    obis_d0_id: smartmeter
    obis_code: "1-0:76.7.0*255"
    unit_of_measurement: W
    accuracy_decimals: 2
    state_class: measurement
    device_class: energy
    value_regex: "\\d{6}\\.\\d{2}\\*W"

#  - platform: obis_d0
#    name: "Smartmeter Status"
#    obis_d0_id: smartmeter
#    obis_code: "1-0:96.5.0*255"
#    value_regex: "[0-9a-fA-F]{8}"
#    format: hex

#  - platform: obis_d0
#    name: "Smartmeter Time of operation"
#    obis_d0_id: smartmeter
#    obis_code: "0-0:96.8.0*255"
#    format: hex
#    disabled_by_default: true
#    entity_category: diagnostic
#    value_regex: "[0-9a-fA-F]{8}"`

**Comment by mampfes** [comment]
Do you get this message every time (= every second) or just every now and then? I also have quite a lot of reading errors with my eBZ DD3 and the Hichi IR Reader. I assume that the Hichi doesn't provide a perfect signal (at least for eBZ), which causes the various reading errors. The OBIS DO component logs **every** reading error - which could be a lot if the signal quality is bad.

What you can try to do is to check the alignment of the IR transmitter in the smart meter and your IR receiver. Check that transmitter and receiver LED are eyeball to eyeball.

**Comment by jcollasius** [comment]
I got multiple errors every second.
I made markings on the Hichi IR Reader and matching markings on the Smartmeter and double-checked the alignment -> the error is gone.

I will compare the vzlogger data (Hichi on MSB) with the ESPHome data (Hichi on Info) for some days and might give feedback later.

I used the following code (might help other users) to see what is going on, on the uart rx:
```
uart:
  id: uart_gpio16
  rx_pin: GPIO16
  baud_rate: 9600
  data_bits: 7
  parity: EVEN
  stop_bits: 1
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);
```

**Comment by mampfes** [comment]
Any feedback?

**Comment by jcollasius** [comment]
Thanks for the reminder,

I ran both esphome_obis_d0 and vzlogger in parallel for quite some time. The data was identical throughout, with no spikes or dropouts.
A short power failure caused the info interface to revert to restricted mode. Since I didn't want to re-enter the PIN into my electricity meter, I now use esphome_obis_d0 on the MSB interface without any problems.

The info interface will be occupied with an ir reader from the electricity provider Tibber from 01.01.2023. If you need an invitation code you can use mine https://invite.tibber.com/3hibqi2h  

Thanks for the great work.

**Comment by mampfes** [comment]
Thanks for the feedback.

BTW: If you are using Tibber you might be interested in having EPEX Spot check data in Home Assistant: I created this integration last week: https://github.com/mampfes/ha_epex_spot
