### ISSUE TITLE
Support for sensor filters?

### ISSUE THREAD

**Issue by grubersh** [mampfes/esphome_obis_d0#6]
Hi,

thanks a lot for this add-on to ESPHome! It really helped me to finally read my EBZ DD3 which doesn't support SML. Does this add-on support sensor filtering? I'd like to reduce the amount of data it sends to HA. Especially the kWh I don't need more than every 60s. 

I've used
`    filters:
    - throttle: 60s`

from https://esphome.io/components/sensor/index.html#throttle 

But it still seems to send the data every second though.

Thanks!

**Comment by mampfes** [comment]
No, I didn't implement any kind of filtering. According to the docu, `throttle`should do the job.

But I don't think that it is worth the spend the effort. I would assume that the overhead for a WLAN message (with all the values in it) is much bigger than the few bytes that are necessary to add an extra value.
