### ISSUE TITLE
IR Lesekopf mit USB (FTDI)

### ISSUE THREAD

**Issue by aquadrat2217** [mampfes/esphome_obis_d0#7]
Hallo Steffen,
ich habe ein einen Lesekopf von Emlog mit USB Ausgang. Kann ich den für dieses Projekt auch nutzen?
VG Andreas

**Comment by mampfes** [comment]
Hi, das wird nicht funktionieren da USB noch dazwischen ist. Du brauchst einen geht einfachen seriellen Leser.
